//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thumper___Leaf_Editor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Thumper___Leaf_Editor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///&quot;masterLvlList&quot;: &quot;CHECKPOINT COLUMN\nIf checked, the lvl will end with a checkpoint. If unchecked, the lvl will not end with a checkpoint and will flow into the next lvl.\n\nPLAY+ COLUMN\nIf checked, the lvl will appear when playing in Play+. If unchecked, it will be left out. This is useful for tutorial levels in Play, and then removing them for Play+.&quot;
        ///}.
        /// </summary>
        internal static string helptext {
            get {
                return ResourceManager.GetString("helptext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  
        ///lattice5.path
        ///tube_hexagon_bright.path
        ///tube_hexagon_chrome.path
        ///lattice4_red.path
        ///spaceship3_chrome.path
        ///spaceship3_dark.path
        ///glass_hex.path
        ///arms_hex.path
        ///occlusion_tube01_psych.path
        ///occlusion_tube_horizontal.path
        ///occlusion_ring_octagon.path
        ///occlusion_tube02_purple.path
        ///lattice4_blue.path
        ///cave_hexagon_bright.path
        ///cave_hexagon_chrome.path
        ///lattice2_green.path
        ///lattice2_red.path
        ///lattice5_blue.path
        ///lattice4_chrome.path
        ///lattice5_chrome.path
        ///lattice5_chrome_large.path
        ///tube_diamond_chrome_ar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string paths {
            get {
                return ResourceManager.GetString("paths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to level_2,drums,crakhed_pattern1.wav
        ///level_2,drums,crakhed_pattern2.wav
        ///level_2,drums,crakhed_pattern3.wav
        ///level_2,drums,crakhed_pattern4.wav
        ///level_2,drums,drums_boss_pattern1.wav
        ///level_2,drums,drums_boss_pattern2.wav
        ///level_2,drums,drums_boss_pattern3.wav
        ///level_2,drums,drums_boss_pattern4.wav
        ///level_2,drums,drums_jagged_pattern1.wav
        ///level_2,drums,drums_jagged_pattern2.wav
        ///level_2,drums,drums_jagged_pattern3.wav
        ///level_2,drums,drums_jagged_pattern4_sparse.wav
        ///level_2,drums,drums_long_pattern1.wav
        ///le [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string samples {
            get {
                return ResourceManager.GetString("samples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRACK EFFECTS
        ///leafname
        ///leafname;pitch;pitch;kTraitFloat;True;1.25;[4,1,2,1,2,&apos;kIntensityScale&apos;,&apos;kIntensityScale&apos;,1,0,1,1,1,1,1,1,0,0,0]
        ///leafname;roll;roll;kTraitFloat;True;0;[4,1,2,1,2,&apos;kIntensityScale&apos;,&apos;kIntensityScale&apos;,1,0,1,1,1,1,1,1,0,0,0]
        ///leafname;turn;turn;kTraitFloat;True;0;[4,1,2,1,2,&apos;kIntensityScale&apos;,&apos;kIntensityScale&apos;,1,0,1,1,1,1,1,1,0,0,0]
        ///leafname;turn_auto;turn_auto;kTraitFloat;True;0;[4,1,2,1,2,&apos;kIntensityScale&apos;,&apos;kIntensityScale&apos;,1,0,1,1,1,1,1,1,0,0,0]
        ///leafname;scale_x;scale_x;kTraitFloat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string track_objects {
            get {
                return ResourceManager.GetString("track_objects", resourceCulture);
            }
        }
    }
}
