//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thumper_Custom_Level_Editor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("64, 0, 0")]
        public global::System.Drawing.Color custom_bgcolor {
            get {
                return ((global::System.Drawing.Color)(this["custom_bgcolor"]));
            }
            set {
                this["custom_bgcolor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80, 0, 0")]
        public global::System.Drawing.Color custom_menucolor {
            get {
                return ((global::System.Drawing.Color)(this["custom_menucolor"]));
            }
            set {
                this["custom_menucolor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55, 55, 55")]
        public global::System.Drawing.Color custom_mastercolor {
            get {
                return ((global::System.Drawing.Color)(this["custom_mastercolor"]));
            }
            set {
                this["custom_mastercolor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55, 55, 55")]
        public global::System.Drawing.Color custom_gatecolor {
            get {
                return ((global::System.Drawing.Color)(this["custom_gatecolor"]));
            }
            set {
                this["custom_gatecolor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55, 55, 55")]
        public global::System.Drawing.Color custom_lvlcolor {
            get {
                return ((global::System.Drawing.Color)(this["custom_lvlcolor"]));
            }
            set {
                this["custom_lvlcolor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55, 55, 55")]
        public global::System.Drawing.Color custom_leafcolor {
            get {
                return ((global::System.Drawing.Color)(this["custom_leafcolor"]));
            }
            set {
                this["custom_leafcolor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55, 55, 55")]
        public global::System.Drawing.Color custom_samplecolor {
            get {
                return ((global::System.Drawing.Color)(this["custom_samplecolor"]));
            }
            set {
                this["custom_samplecolor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string game_dir {
            get {
                return ((string)(this["game_dir"]));
            }
            set {
                this["game_dir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("76, 66")]
        public global::System.Drawing.Size beeblesize {
            get {
                return ((global::System.Drawing.Size)(this["beeblesize"]));
            }
            set {
                this["beeblesize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("620, 1")]
        public global::System.Drawing.Point beebleloc {
            get {
                return ((global::System.Drawing.Point)(this["beebleloc"]));
            }
            set {
                this["beebleloc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CornflowerBlue")]
        public global::System.Drawing.Color custom_activecolor {
            get {
                return ((global::System.Drawing.Color)(this["custom_activecolor"]));
            }
            set {
                this["custom_activecolor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int leafzoom {
            get {
                return ((int)(this["leafzoom"]));
            }
            set {
                this["leafzoom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int lvlzoom {
            get {
                return ((int)(this["lvlzoom"]));
            }
            set {
                this["lvlzoom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<string> Recentfiles {
            get {
                return ((global::System.Collections.Generic.List<string>)(this["Recentfiles"]));
            }
            set {
                this["Recentfiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.Windows.Forms.Keys> KeyBinds {
            get {
                return ((global::System.Collections.Generic.List<System.Windows.Forms.Keys>)(this["KeyBinds"]));
            }
            set {
                this["KeyBinds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool muteapplication {
            get {
                return ((bool)(this["muteapplication"]));
            }
            set {
                this["muteapplication"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool leafautoinsert {
            get {
                return ((bool)(this["leafautoinsert"]));
            }
            set {
                this["leafautoinsert"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int leafzoomvert {
            get {
                return ((int)(this["leafzoomvert"]));
            }
            set {
                this["leafzoomvert"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("--")]
        public string version {
            get {
                return ((string)(this["version"]));
            }
            set {
                this["version"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool firstrun {
            get {
                return ((bool)(this["firstrun"]));
            }
            set {
                this["firstrun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<int> colordialogcustomcolors {
            get {
                return ((global::System.Collections.Generic.List<int>)(this["colordialogcustomcolors"]));
            }
            set {
                this["colordialogcustomcolors"] = value;
            }
        }
    }
}
