//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thumper_Custom_Level_Editor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string game_dir {
            get {
                return ((string)(this["game_dir"]));
            }
            set {
                this["game_dir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("76, 66")]
        public global::System.Drawing.Size beeblesize {
            get {
                return ((global::System.Drawing.Size)(this["beeblesize"]));
            }
            set {
                this["beeblesize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("620, 1")]
        public global::System.Drawing.Point beebleloc {
            get {
                return ((global::System.Drawing.Point)(this["beebleloc"]));
            }
            set {
                this["beebleloc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int leafzoom {
            get {
                return ((int)(this["leafzoom"]));
            }
            set {
                this["leafzoom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int lvlzoom {
            get {
                return ((int)(this["lvlzoom"]));
            }
            set {
                this["lvlzoom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<string> Recentfiles {
            get {
                return ((global::System.Collections.Generic.List<string>)(this["Recentfiles"]));
            }
            set {
                this["Recentfiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.Windows.Forms.Keys> KeyBinds {
            get {
                return ((global::System.Collections.Generic.List<System.Windows.Forms.Keys>)(this["KeyBinds"]));
            }
            set {
                this["KeyBinds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool muteapplication {
            get {
                return ((bool)(this["muteapplication"]));
            }
            set {
                this["muteapplication"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool leafautoinsert {
            get {
                return ((bool)(this["leafautoinsert"]));
            }
            set {
                this["leafautoinsert"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int leafzoomvert {
            get {
                return ((int)(this["leafzoomvert"]));
            }
            set {
                this["leafzoomvert"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("--")]
        public string version {
            get {
                return ((string)(this["version"]));
            }
            set {
                this["version"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool firstrun {
            get {
                return ((bool)(this["firstrun"]));
            }
            set {
                this["firstrun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<int> colordialogcustomcolors {
            get {
                return ((global::System.Collections.Generic.List<int>)(this["colordialogcustomcolors"]));
            }
            set {
                this["colordialogcustomcolors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LeafOptionShowCategory {
            get {
                return ((bool)(this["LeafOptionShowCategory"]));
            }
            set {
                this["LeafOptionShowCategory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LeafOptionShowGrid {
            get {
                return ((bool)(this["LeafOptionShowGrid"]));
            }
            set {
                this["LeafOptionShowGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LeafOptionConnectBars {
            get {
                return ((bool)(this["LeafOptionConnectBars"]));
            }
            set {
                this["LeafOptionConnectBars"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LeafOptionShowLane {
            get {
                return ((bool)(this["LeafOptionShowLane"]));
            }
            set {
                this["LeafOptionShowLane"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LeafOptionEaseDots {
            get {
                return ((bool)(this["LeafOptionEaseDots"]));
            }
            set {
                this["LeafOptionEaseDots"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LeafOptionThinBars {
            get {
                return ((bool)(this["LeafOptionThinBars"]));
            }
            set {
                this["LeafOptionThinBars"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LeafOptionShowWave {
            get {
                return ((bool)(this["LeafOptionShowWave"]));
            }
            set {
                this["LeafOptionShowWave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80, 0, 0")]
        public global::System.Drawing.Color ColorMainMenuBar {
            get {
                return ((global::System.Drawing.Color)(this["ColorMainMenuBar"]));
            }
            set {
                this["ColorMainMenuBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("31, 31, 31")]
        public global::System.Drawing.Color ColorMainSubMenubar {
            get {
                return ((global::System.Drawing.Color)(this["ColorMainSubMenubar"]));
            }
            set {
                this["ColorMainSubMenubar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("31, 31, 31")]
        public global::System.Drawing.Color ColorMainBG {
            get {
                return ((global::System.Drawing.Color)(this["ColorMainBG"]));
            }
            set {
                this["ColorMainBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55, 55, 55")]
        public global::System.Drawing.Color ColorLeafBG {
            get {
                return ((global::System.Drawing.Color)(this["ColorLeafBG"]));
            }
            set {
                this["ColorLeafBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10, 10, 10")]
        public global::System.Drawing.Color ColorLeafSeqBG {
            get {
                return ((global::System.Drawing.Color)(this["ColorLeafSeqBG"]));
            }
            set {
                this["ColorLeafSeqBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55, 55, 55")]
        public global::System.Drawing.Color ColorLeafTimeSig1 {
            get {
                return ((global::System.Drawing.Color)(this["ColorLeafTimeSig1"]));
            }
            set {
                this["ColorLeafTimeSig1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("45, 45, 45")]
        public global::System.Drawing.Color ColorLeafTimeSig2 {
            get {
                return ((global::System.Drawing.Color)(this["ColorLeafTimeSig2"]));
            }
            set {
                this["ColorLeafTimeSig2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("31, 31, 31")]
        public global::System.Drawing.Color ColorLeafRawBG {
            get {
                return ((global::System.Drawing.Color)(this["ColorLeafRawBG"]));
            }
            set {
                this["ColorLeafRawBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color ColorLeafRawText {
            get {
                return ((global::System.Drawing.Color)(this["ColorLeafRawText"]));
            }
            set {
                this["ColorLeafRawText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55, 55, 55")]
        public global::System.Drawing.Color ColorLvlBG {
            get {
                return ((global::System.Drawing.Color)(this["ColorLvlBG"]));
            }
            set {
                this["ColorLvlBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10, 10, 10")]
        public global::System.Drawing.Color ColorLvlLeafBG {
            get {
                return ((global::System.Drawing.Color)(this["ColorLvlLeafBG"]));
            }
            set {
                this["ColorLvlLeafBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10, 10, 10")]
        public global::System.Drawing.Color ColorLvlTunnelBG {
            get {
                return ((global::System.Drawing.Color)(this["ColorLvlTunnelBG"]));
            }
            set {
                this["ColorLvlTunnelBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10, 10, 10")]
        public global::System.Drawing.Color ColorLvlLoopsBG {
            get {
                return ((global::System.Drawing.Color)(this["ColorLvlLoopsBG"]));
            }
            set {
                this["ColorLvlLoopsBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55, 55, 55")]
        public global::System.Drawing.Color ColorGateBG {
            get {
                return ((global::System.Drawing.Color)(this["ColorGateBG"]));
            }
            set {
                this["ColorGateBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10, 10, 10")]
        public global::System.Drawing.Color ColorGateLvlBG {
            get {
                return ((global::System.Drawing.Color)(this["ColorGateLvlBG"]));
            }
            set {
                this["ColorGateLvlBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55, 55, 55")]
        public global::System.Drawing.Color ColorMasterBG {
            get {
                return ((global::System.Drawing.Color)(this["ColorMasterBG"]));
            }
            set {
                this["ColorMasterBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10, 10, 10")]
        public global::System.Drawing.Color ColorMasterLvlBG {
            get {
                return ((global::System.Drawing.Color)(this["ColorMasterLvlBG"]));
            }
            set {
                this["ColorMasterLvlBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55, 55, 55")]
        public global::System.Drawing.Color ColorSampleBG {
            get {
                return ((global::System.Drawing.Color)(this["ColorSampleBG"]));
            }
            set {
                this["ColorSampleBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10, 10, 10")]
        public global::System.Drawing.Color ColorSampleListBG {
            get {
                return ((global::System.Drawing.Color)(this["ColorSampleListBG"]));
            }
            set {
                this["ColorSampleListBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ColorWaveformBG {
            get {
                return ((global::System.Drawing.Color)(this["ColorWaveformBG"]));
            }
            set {
                this["ColorWaveformBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55, 55, 55")]
        public global::System.Drawing.Color ColorProjectExplorerBG {
            get {
                return ((global::System.Drawing.Color)(this["ColorProjectExplorerBG"]));
            }
            set {
                this["ColorProjectExplorerBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("31, 31, 31")]
        public global::System.Drawing.Color ColorRawBG {
            get {
                return ((global::System.Drawing.Color)(this["ColorRawBG"]));
            }
            set {
                this["ColorRawBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color ColorRawText {
            get {
                return ((global::System.Drawing.Color)(this["ColorRawText"]));
            }
            set {
                this["ColorRawText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-")]
        public string UserKeybinds {
            get {
                return ((string)(this["UserKeybinds"]));
            }
            set {
                this["UserKeybinds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("56, 56, 56")]
        public global::System.Drawing.Color ColorProjExpHighlight {
            get {
                return ((global::System.Drawing.Color)(this["ColorProjExpHighlight"]));
            }
            set {
                this["ColorProjExpHighlight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color ColorProjExpText {
            get {
                return ((global::System.Drawing.Color)(this["ColorProjExpText"]));
            }
            set {
                this["ColorProjExpText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int ZoomHoriz {
            get {
                return ((int)(this["ZoomHoriz"]));
            }
            set {
                this["ZoomHoriz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int ZoomVert {
            get {
                return ((int)(this["ZoomVert"]));
            }
            set {
                this["ZoomVert"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RuntimeAsk {
            get {
                return ((bool)(this["RuntimeAsk"]));
            }
            set {
                this["RuntimeAsk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RuntimeSkip {
            get {
                return ((bool)(this["RuntimeSkip"]));
            }
            set {
                this["RuntimeSkip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LeafHideRaw {
            get {
                return ((bool)(this["LeafHideRaw"]));
            }
            set {
                this["LeafHideRaw"] = value;
            }
        }
    }
}
