//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thumper_Custom_Level_Editor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1430, 555")]
        public global::System.Drawing.Size leafeditorsize {
            get {
                return ((global::System.Drawing.Size)(this["leafeditorsize"]));
            }
            set {
                this["leafeditorsize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("307, 418")]
        public global::System.Drawing.Point leafeditorloc {
            get {
                return ((global::System.Drawing.Point)(this["leafeditorloc"]));
            }
            set {
                this["leafeditorloc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("997, 383")]
        public global::System.Drawing.Size lvleditorsize {
            get {
                return ((global::System.Drawing.Size)(this["lvleditorsize"]));
            }
            set {
                this["lvleditorsize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("864, 29")]
        public global::System.Drawing.Point lvleditorloc {
            get {
                return ((global::System.Drawing.Point)(this["lvleditorloc"]));
            }
            set {
                this["lvleditorloc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("386, 383")]
        public global::System.Drawing.Size gateeditorsize {
            get {
                return ((global::System.Drawing.Size)(this["gateeditorsize"]));
            }
            set {
                this["gateeditorsize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("472, 29")]
        public global::System.Drawing.Point gateeditorloc {
            get {
                return ((global::System.Drawing.Point)(this["gateeditorloc"]));
            }
            set {
                this["gateeditorloc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("462, 383")]
        public global::System.Drawing.Size mastereditorsize {
            get {
                return ((global::System.Drawing.Size)(this["mastereditorsize"]));
            }
            set {
                this["mastereditorsize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4, 29")]
        public global::System.Drawing.Point mastereditorloc {
            get {
                return ((global::System.Drawing.Point)(this["mastereditorloc"]));
            }
            set {
                this["mastereditorloc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("297, 444")]
        public global::System.Drawing.Size foldersize {
            get {
                return ((global::System.Drawing.Size)(this["foldersize"]));
            }
            set {
                this["foldersize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4, 418")]
        public global::System.Drawing.Point folderloc {
            get {
                return ((global::System.Drawing.Point)(this["folderloc"]));
            }
            set {
                this["folderloc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("450, 380")]
        public global::System.Drawing.Size sampleeditorsize {
            get {
                return ((global::System.Drawing.Size)(this["sampleeditorsize"]));
            }
            set {
                this["sampleeditorsize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("370, 100")]
        public global::System.Drawing.Point sampleeditorloc {
            get {
                return ((global::System.Drawing.Point)(this["sampleeditorloc"]));
            }
            set {
                this["sampleeditorloc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("64, 0, 0")]
        public global::System.Drawing.Color custom_bgcolor {
            get {
                return ((global::System.Drawing.Color)(this["custom_bgcolor"]));
            }
            set {
                this["custom_bgcolor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Maroon")]
        public global::System.Drawing.Color custom_menucolor {
            get {
                return ((global::System.Drawing.Color)(this["custom_menucolor"]));
            }
            set {
                this["custom_menucolor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55, 55, 55")]
        public global::System.Drawing.Color custom_mastercolor {
            get {
                return ((global::System.Drawing.Color)(this["custom_mastercolor"]));
            }
            set {
                this["custom_mastercolor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool leafeditorvisible {
            get {
                return ((bool)(this["leafeditorvisible"]));
            }
            set {
                this["leafeditorvisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool lvleditorvisible {
            get {
                return ((bool)(this["lvleditorvisible"]));
            }
            set {
                this["lvleditorvisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool gateeditorvisible {
            get {
                return ((bool)(this["gateeditorvisible"]));
            }
            set {
                this["gateeditorvisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool mastereditorvisible {
            get {
                return ((bool)(this["mastereditorvisible"]));
            }
            set {
                this["mastereditorvisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool workingfoldervisible {
            get {
                return ((bool)(this["workingfoldervisible"]));
            }
            set {
                this["workingfoldervisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool sampleeditorvisible {
            get {
                return ((bool)(this["sampleeditorvisible"]));
            }
            set {
                this["sampleeditorvisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55, 55, 55")]
        public global::System.Drawing.Color custom_gatecolor {
            get {
                return ((global::System.Drawing.Color)(this["custom_gatecolor"]));
            }
            set {
                this["custom_gatecolor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55, 55, 55")]
        public global::System.Drawing.Color custom_lvlcolor {
            get {
                return ((global::System.Drawing.Color)(this["custom_lvlcolor"]));
            }
            set {
                this["custom_lvlcolor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55, 55, 55")]
        public global::System.Drawing.Color custom_leafcolor {
            get {
                return ((global::System.Drawing.Color)(this["custom_leafcolor"]));
            }
            set {
                this["custom_leafcolor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55, 55, 55")]
        public global::System.Drawing.Color custom_samplecolor {
            get {
                return ((global::System.Drawing.Color)(this["custom_samplecolor"]));
            }
            set {
                this["custom_samplecolor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string game_dir {
            get {
                return ((string)(this["game_dir"]));
            }
            set {
                this["game_dir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("76, 66")]
        public global::System.Drawing.Size beeblesize {
            get {
                return ((global::System.Drawing.Size)(this["beeblesize"]));
            }
            set {
                this["beeblesize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("620, 1")]
        public global::System.Drawing.Point beebleloc {
            get {
                return ((global::System.Drawing.Point)(this["beebleloc"]));
            }
            set {
                this["beebleloc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("empty")]
        public string dock1 {
            get {
                return ((string)(this["dock1"]));
            }
            set {
                this["dock1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("empty")]
        public string dock2 {
            get {
                return ((string)(this["dock2"]));
            }
            set {
                this["dock2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("empty")]
        public string dock3 {
            get {
                return ((string)(this["dock3"]));
            }
            set {
                this["dock3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("empty")]
        public string dock4 {
            get {
                return ((string)(this["dock4"]));
            }
            set {
                this["dock4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("empty")]
        public string dock5 {
            get {
                return ((string)(this["dock5"]));
            }
            set {
                this["dock5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("empty")]
        public string dock6 {
            get {
                return ((string)(this["dock6"]));
            }
            set {
                this["dock6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int splitterHorz1 {
            get {
                return ((int)(this["splitterHorz1"]));
            }
            set {
                this["splitterHorz1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int splitterVert1 {
            get {
                return ((int)(this["splitterVert1"]));
            }
            set {
                this["splitterVert1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int splitterVert2 {
            get {
                return ((int)(this["splitterVert2"]));
            }
            set {
                this["splitterVert2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int splitterVert3 {
            get {
                return ((int)(this["splitterVert3"]));
            }
            set {
                this["splitterVert3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int splitterVert4 {
            get {
                return ((int)(this["splitterVert4"]));
            }
            set {
                this["splitterVert4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CornflowerBlue")]
        public global::System.Drawing.Color custom_activecolor {
            get {
                return ((global::System.Drawing.Color)(this["custom_activecolor"]));
            }
            set {
                this["custom_activecolor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int leafzoom {
            get {
                return ((int)(this["leafzoom"]));
            }
            set {
                this["leafzoom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int lvlzoom {
            get {
                return ((int)(this["lvlzoom"]));
            }
            set {
                this["lvlzoom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<string> Recentfiles {
            get {
                return ((global::System.Collections.Generic.List<string>)(this["Recentfiles"]));
            }
            set {
                this["Recentfiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.Windows.Forms.Keys> KeyBinds {
            get {
                return ((global::System.Collections.Generic.List<System.Windows.Forms.Keys>)(this["KeyBinds"]));
            }
            set {
                this["KeyBinds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool muteapplication {
            get {
                return ((bool)(this["muteapplication"]));
            }
            set {
                this["muteapplication"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool leafautoinsert {
            get {
                return ((bool)(this["leafautoinsert"]));
            }
            set {
                this["leafautoinsert"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int leafzoomvert {
            get {
                return ((int)(this["leafzoomvert"]));
            }
            set {
                this["leafzoomvert"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("--")]
        public string version {
            get {
                return ((string)(this["version"]));
            }
            set {
                this["version"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool firstrun {
            get {
                return ((bool)(this["firstrun"]));
            }
            set {
                this["firstrun"] = value;
            }
        }
    }
}
