//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thumper_Custom_Level_Editor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string game_dir {
            get {
                return ((string)(this["game_dir"]));
            }
            set {
                this["game_dir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("76, 66")]
        public global::System.Drawing.Size beeblesize {
            get {
                return ((global::System.Drawing.Size)(this["beeblesize"]));
            }
            set {
                this["beeblesize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("620, 1")]
        public global::System.Drawing.Point beebleloc {
            get {
                return ((global::System.Drawing.Point)(this["beebleloc"]));
            }
            set {
                this["beebleloc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int leafzoom {
            get {
                return ((int)(this["leafzoom"]));
            }
            set {
                this["leafzoom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int lvlzoom {
            get {
                return ((int)(this["lvlzoom"]));
            }
            set {
                this["lvlzoom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<string> Recentfiles {
            get {
                return ((global::System.Collections.Generic.List<string>)(this["Recentfiles"]));
            }
            set {
                this["Recentfiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.Windows.Forms.Keys> KeyBinds {
            get {
                return ((global::System.Collections.Generic.List<System.Windows.Forms.Keys>)(this["KeyBinds"]));
            }
            set {
                this["KeyBinds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool muteapplication {
            get {
                return ((bool)(this["muteapplication"]));
            }
            set {
                this["muteapplication"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool leafautoinsert {
            get {
                return ((bool)(this["leafautoinsert"]));
            }
            set {
                this["leafautoinsert"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int leafzoomvert {
            get {
                return ((int)(this["leafzoomvert"]));
            }
            set {
                this["leafzoomvert"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("--")]
        public string version {
            get {
                return ((string)(this["version"]));
            }
            set {
                this["version"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool firstrun {
            get {
                return ((bool)(this["firstrun"]));
            }
            set {
                this["firstrun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<int> colordialogcustomcolors {
            get {
                return ((global::System.Collections.Generic.List<int>)(this["colordialogcustomcolors"]));
            }
            set {
                this["colordialogcustomcolors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LeafOptionShowCategory {
            get {
                return ((bool)(this["LeafOptionShowCategory"]));
            }
            set {
                this["LeafOptionShowCategory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LeafOptionShowGrid {
            get {
                return ((bool)(this["LeafOptionShowGrid"]));
            }
            set {
                this["LeafOptionShowGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LeafOptionConnectBars {
            get {
                return ((bool)(this["LeafOptionConnectBars"]));
            }
            set {
                this["LeafOptionConnectBars"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LeafOptionShowLane {
            get {
                return ((bool)(this["LeafOptionShowLane"]));
            }
            set {
                this["LeafOptionShowLane"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LeafOptionEaseDots {
            get {
                return ((bool)(this["LeafOptionEaseDots"]));
            }
            set {
                this["LeafOptionEaseDots"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LeafOptionThinBars {
            get {
                return ((bool)(this["LeafOptionThinBars"]));
            }
            set {
                this["LeafOptionThinBars"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LeafOptionShowWave {
            get {
                return ((bool)(this["LeafOptionShowWave"]));
            }
            set {
                this["LeafOptionShowWave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80, 0, 0")]
        public global::System.Drawing.Color ColorMainMenuBar {
            get {
                return ((global::System.Drawing.Color)(this["ColorMainMenuBar"]));
            }
            set {
                this["ColorMainMenuBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("31, 31, 31")]
        public global::System.Drawing.Color ColorMainSubMenubar {
            get {
                return ((global::System.Drawing.Color)(this["ColorMainSubMenubar"]));
            }
            set {
                this["ColorMainSubMenubar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("31, 31, 31")]
        public global::System.Drawing.Color ColorMainBG {
            get {
                return ((global::System.Drawing.Color)(this["ColorMainBG"]));
            }
            set {
                this["ColorMainBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55, 55, 55")]
        public global::System.Drawing.Color ColorLeafBG {
            get {
                return ((global::System.Drawing.Color)(this["ColorLeafBG"]));
            }
            set {
                this["ColorLeafBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10, 10, 10")]
        public global::System.Drawing.Color ColorLeafSeqBG {
            get {
                return ((global::System.Drawing.Color)(this["ColorLeafSeqBG"]));
            }
            set {
                this["ColorLeafSeqBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55, 55, 55")]
        public global::System.Drawing.Color ColorLeafTimeSig1 {
            get {
                return ((global::System.Drawing.Color)(this["ColorLeafTimeSig1"]));
            }
            set {
                this["ColorLeafTimeSig1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("45, 45, 45")]
        public global::System.Drawing.Color ColorLeafTimeSig2 {
            get {
                return ((global::System.Drawing.Color)(this["ColorLeafTimeSig2"]));
            }
            set {
                this["ColorLeafTimeSig2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("31, 31, 31")]
        public global::System.Drawing.Color ColorLeafRawBG {
            get {
                return ((global::System.Drawing.Color)(this["ColorLeafRawBG"]));
            }
            set {
                this["ColorLeafRawBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color ColorLeafRawText {
            get {
                return ((global::System.Drawing.Color)(this["ColorLeafRawText"]));
            }
            set {
                this["ColorLeafRawText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55, 55, 55")]
        public global::System.Drawing.Color ColorLvlBG {
            get {
                return ((global::System.Drawing.Color)(this["ColorLvlBG"]));
            }
            set {
                this["ColorLvlBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10, 10, 10")]
        public global::System.Drawing.Color ColorLvlLeafBG {
            get {
                return ((global::System.Drawing.Color)(this["ColorLvlLeafBG"]));
            }
            set {
                this["ColorLvlLeafBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10, 10, 10")]
        public global::System.Drawing.Color ColorLvlTunnelBG {
            get {
                return ((global::System.Drawing.Color)(this["ColorLvlTunnelBG"]));
            }
            set {
                this["ColorLvlTunnelBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10, 10, 10")]
        public global::System.Drawing.Color ColorLvlLoopsBG {
            get {
                return ((global::System.Drawing.Color)(this["ColorLvlLoopsBG"]));
            }
            set {
                this["ColorLvlLoopsBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55, 55, 55")]
        public global::System.Drawing.Color ColorGateBG {
            get {
                return ((global::System.Drawing.Color)(this["ColorGateBG"]));
            }
            set {
                this["ColorGateBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10, 10, 10")]
        public global::System.Drawing.Color ColorGateLvlBG {
            get {
                return ((global::System.Drawing.Color)(this["ColorGateLvlBG"]));
            }
            set {
                this["ColorGateLvlBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55, 55, 55")]
        public global::System.Drawing.Color ColorMasterBG {
            get {
                return ((global::System.Drawing.Color)(this["ColorMasterBG"]));
            }
            set {
                this["ColorMasterBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10, 10, 10")]
        public global::System.Drawing.Color ColorMasterLvlBG {
            get {
                return ((global::System.Drawing.Color)(this["ColorMasterLvlBG"]));
            }
            set {
                this["ColorMasterLvlBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55, 55, 55")]
        public global::System.Drawing.Color ColorSampleBG {
            get {
                return ((global::System.Drawing.Color)(this["ColorSampleBG"]));
            }
            set {
                this["ColorSampleBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10, 10, 10")]
        public global::System.Drawing.Color ColorSampleListBG {
            get {
                return ((global::System.Drawing.Color)(this["ColorSampleListBG"]));
            }
            set {
                this["ColorSampleListBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ColorWaveformBG {
            get {
                return ((global::System.Drawing.Color)(this["ColorWaveformBG"]));
            }
            set {
                this["ColorWaveformBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("31, 31, 31")]
        public global::System.Drawing.Color ColorProjectExplorerBG {
            get {
                return ((global::System.Drawing.Color)(this["ColorProjectExplorerBG"]));
            }
            set {
                this["ColorProjectExplorerBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("31, 31, 31")]
        public global::System.Drawing.Color ColorRawBG {
            get {
                return ((global::System.Drawing.Color)(this["ColorRawBG"]));
            }
            set {
                this["ColorRawBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color ColorRawText {
            get {
                return ((global::System.Drawing.Color)(this["ColorRawText"]));
            }
            set {
                this["ColorRawText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-")]
        public string UserKeybinds {
            get {
                return ((string)(this["UserKeybinds"]));
            }
            set {
                this["UserKeybinds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("56, 56, 56")]
        public global::System.Drawing.Color ColorProjExpHighlight {
            get {
                return ((global::System.Drawing.Color)(this["ColorProjExpHighlight"]));
            }
            set {
                this["ColorProjExpHighlight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color ColorProjExpText {
            get {
                return ((global::System.Drawing.Color)(this["ColorProjExpText"]));
            }
            set {
                this["ColorProjExpText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int ZoomHoriz {
            get {
                return ((int)(this["ZoomHoriz"]));
            }
            set {
                this["ZoomHoriz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int ZoomVert {
            get {
                return ((int)(this["ZoomVert"]));
            }
            set {
                this["ZoomVert"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RuntimeAsk {
            get {
                return ((bool)(this["RuntimeAsk"]));
            }
            set {
                this["RuntimeAsk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RuntimeSkip {
            get {
                return ((bool)(this["RuntimeSkip"]));
            }
            set {
                this["RuntimeSkip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LeafHideRaw {
            get {
                return ((bool)(this["LeafHideRaw"]));
            }
            set {
                this["LeafHideRaw"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int VolKey1 {
            get {
                return ((int)(this["VolKey1"]));
            }
            set {
                this["VolKey1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("35")]
        public int VolKey2 {
            get {
                return ((int)(this["VolKey2"]));
            }
            set {
                this["VolKey2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int VolKey3 {
            get {
                return ((int)(this["VolKey3"]));
            }
            set {
                this["VolKey3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int VolKey4 {
            get {
                return ((int)(this["VolKey4"]));
            }
            set {
                this["VolKey4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("35")]
        public int VolKey5 {
            get {
                return ((int)(this["VolKey5"]));
            }
            set {
                this["VolKey5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70")]
        public int VolKey6 {
            get {
                return ((int)(this["VolKey6"]));
            }
            set {
                this["VolKey6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int VolKey7 {
            get {
                return ((int)(this["VolKey7"]));
            }
            set {
                this["VolKey7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int VolKey8 {
            get {
                return ((int)(this["VolKey8"]));
            }
            set {
                this["VolKey8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int VolKey9 {
            get {
                return ((int)(this["VolKey9"]));
            }
            set {
                this["VolKey9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("65")]
        public int VolKey10 {
            get {
                return ((int)(this["VolKey10"]));
            }
            set {
                this["VolKey10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("48")]
        public int VolKey11 {
            get {
                return ((int)(this["VolKey11"]));
            }
            set {
                this["VolKey11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("65")]
        public int VolKey12 {
            get {
                return ((int)(this["VolKey12"]));
            }
            set {
                this["VolKey12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int VolKey13 {
            get {
                return ((int)(this["VolKey13"]));
            }
            set {
                this["VolKey13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55")]
        public int VolKey14 {
            get {
                return ((int)(this["VolKey14"]));
            }
            set {
                this["VolKey14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55")]
        public int VolKey15 {
            get {
                return ((int)(this["VolKey15"]));
            }
            set {
                this["VolKey15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("65")]
        public int VolKey16 {
            get {
                return ((int)(this["VolKey16"]));
            }
            set {
                this["VolKey16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("89")]
        public int VolKey17 {
            get {
                return ((int)(this["VolKey17"]));
            }
            set {
                this["VolKey17"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int VolKey18 {
            get {
                return ((int)(this["VolKey18"]));
            }
            set {
                this["VolKey18"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int VolKey19 {
            get {
                return ((int)(this["VolKey19"]));
            }
            set {
                this["VolKey19"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int VolKey20 {
            get {
                return ((int)(this["VolKey20"]));
            }
            set {
                this["VolKey20"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int VolKey100 {
            get {
                return ((int)(this["VolKey100"]));
            }
            set {
                this["VolKey100"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int VolKey99 {
            get {
                return ((int)(this["VolKey99"]));
            }
            set {
                this["VolKey99"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<string> SequencerFavorites {
            get {
                return ((global::System.Collections.Generic.List<string>)(this["SequencerFavorites"]));
            }
            set {
                this["SequencerFavorites"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("45")]
        public int VolKey21 {
            get {
                return ((int)(this["VolKey21"]));
            }
            set {
                this["VolKey21"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PreviewTunnel {
            get {
                return ((bool)(this["PreviewTunnel"]));
            }
            set {
                this["PreviewTunnel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ChunkShowName {
            get {
                return ((bool)(this["ChunkShowName"]));
            }
            set {
                this["ChunkShowName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ChunkShowBeats {
            get {
                return ((bool)(this["ChunkShowBeats"]));
            }
            set {
                this["ChunkShowBeats"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ChunkShowTime {
            get {
                return ((bool)(this["ChunkShowTime"]));
            }
            set {
                this["ChunkShowTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LeafOptionVerticalCells {
            get {
                return ((bool)(this["LeafOptionVerticalCells"]));
            }
            set {
                this["LeafOptionVerticalCells"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ColorTuningBG {
            get {
                return ((global::System.Drawing.Color)(this["ColorTuningBG"]));
            }
            set {
                this["ColorTuningBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color ColorTuningLine {
            get {
                return ((global::System.Drawing.Color)(this["ColorTuningLine"]));
            }
            set {
                this["ColorTuningLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 0, 128")]
        public global::System.Drawing.Color ColorTuningPoint {
            get {
                return ((global::System.Drawing.Color)(this["ColorTuningPoint"]));
            }
            set {
                this["ColorTuningPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80, 80, 80")]
        public global::System.Drawing.Color ColorTuningMaxMin {
            get {
                return ((global::System.Drawing.Color)(this["ColorTuningMaxMin"]));
            }
            set {
                this["ColorTuningMaxMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color ColorTuningFont {
            get {
                return ((global::System.Drawing.Color)(this["ColorTuningFont"]));
            }
            set {
                this["ColorTuningFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LeafOptionAutoPlace {
            get {
                return ((bool)(this["LeafOptionAutoPlace"]));
            }
            set {
                this["LeafOptionAutoPlace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-")]
        public string UserRandomValues {
            get {
                return ((string)(this["UserRandomValues"]));
            }
            set {
                this["UserRandomValues"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Linear")]
        public string LeafOptionInterp {
            get {
                return ((string)(this["LeafOptionInterp"]));
            }
            set {
                this["LeafOptionInterp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ColorLeafBasicBG {
            get {
                return ((global::System.Drawing.Color)(this["ColorLeafBasicBG"]));
            }
            set {
                this["ColorLeafBasicBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("110, 110, 110")]
        public global::System.Drawing.Color ColorLeafBasicGrid {
            get {
                return ((global::System.Drawing.Color)(this["ColorLeafBasicGrid"]));
            }
            set {
                this["ColorLeafBasicGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LeafOptionPlaybackScroll {
            get {
                return ((bool)(this["LeafOptionPlaybackScroll"]));
            }
            set {
                this["LeafOptionPlaybackScroll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool muteduck {
            get {
                return ((bool)(this["muteduck"]));
            }
            set {
                this["muteduck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LeafOptionCategoryIcon {
            get {
                return ((bool)(this["LeafOptionCategoryIcon"]));
            }
            set {
                this["LeafOptionCategoryIcon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double ProportionLeafContentMain {
            get {
                return ((double)(this["ProportionLeafContentMain"]));
            }
            set {
                this["ProportionLeafContentMain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.13")]
        public double ProportionLeafObjects {
            get {
                return ((double)(this["ProportionLeafObjects"]));
            }
            set {
                this["ProportionLeafObjects"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double ProportionLeafPropertyGrid {
            get {
                return ((double)(this["ProportionLeafPropertyGrid"]));
            }
            set {
                this["ProportionLeafPropertyGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.2")]
        public double ProportionLeafMasterView {
            get {
                return ((double)(this["ProportionLeafMasterView"]));
            }
            set {
                this["ProportionLeafMasterView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LeafOptionScaleHeader {
            get {
                return ((bool)(this["LeafOptionScaleHeader"]));
            }
            set {
                this["LeafOptionScaleHeader"] = value;
            }
        }
    }
}
